### ISSUE TITLE
我看代码中进行判断是否是“.exe.manifest”结尾的文件，意义在哪儿呢，我实际提取出来的文件并没有".exe.manifest"的文件

### ISSUE THREAD

**Issue by pcorvoh** [MrWQ/reverse_pyinstaller#1]
代码提取出来的文件并没有“.exe.manifest”结尾的文件，导致没有办法获取到文件
``` Python
You can now use a python decompiler on the pyc files within the extracted directory
Traceback (most recent call last):
  File "E:\Masturbator_Script\exe_to_py\reverse_pyinstaller\reverse_pyexe.py", line 137, in <module>
    main_file_path = os.path.join(extracted_dir, main_file)  # 入口文件路径
  File "E:\soft\Python3.9\lib\ntpath.py", line 117, in join
    genericpath._check_arg_types('join', path, *paths)
  File "E:\soft\Python3.9\lib\genericpath.py", line 152, in _check_arg_types
    raise TypeError(f'{funcname}() argument must be str, bytes, or '
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'NoneType'
```
我不知道这个文件是用来干什么的，我看教程也没有需要使用到这个文件

**Comment by MrWQ** [comment]
只能还原reverse_pyinstaller打包的exe，其它方式编译的exe不支持
